const products = [
    {id: 1, name: 'Guayos Sin Bota', plataforma: 'Pofesional', unidades: 60, genero: 'Guayos', price: 400.00, image: "Images/Guayos Sin Bota.jpg" },
    {id: 2, name: 'Guayos Con Bota', plataforma: 'Profesional', unidades: 60, genero: 'Guayos', price: 400.000, image: "Images/Guayos Con Bota.jpg" },
    {id: 3, name: 'Guayos Semi Bota', plataforma: 'Profesional', unidades: 60, genero: 'Guayos', price: 400.000,  image: "Images/Guayos Semi Bota.jpg" },
    {id: 7, name: 'Camisetas', plataforma: 'Tela Fria', unidades: 60, genero: 'Ropa Deportiva', price: 300.00, image: "Images/Camisetas de futbol.jpg"},
    {id: 8, name: 'Pantaloneta', plataforma: 'Algodón', unidades: 60, genero: 'Ropa Deportiva', price: 250.00, image: "Images/pantaloneta.jpg" },
    {id: 9, name: 'Medias Antideslizante', plataforma: 'Tela Antideslizante', unidades: 60, genero: 'Ropa Deportiva', price: 300.00, image: "Images/Medias Antideslizante.jpg"},
    {id: 10, name: 'Conjunto Deportivo Hombre', plataforma: 'Tela Fria', unidades: 60, genero: 'Ropa Deportiva', price: 300.00, image: "Images/Conjunto Deportivo Hombre.jpg"},
    {id: 11, name: 'Conjunto Deportivo Mujer', plataforma: 'Tela Fria', unidades: 60, genero: 'Ropa Deportiva', price: 300.00, image: "Images/Conjunto Deportivo Mujer.jpg"},
    {id: 12, name: 'Licra Superior', plataforma: 'Tela Fria', unidades: 60, genero: 'Ropa Deportiva', price: 250.00, image: "Images/Licra Superior.jpg"},
    {id: 13, name: 'Licra Piernas', plataforma: 'Tela Fria', unidades: 60, genero: 'Ropa Deportiva', price: 250.00, image: "Images/Licra Piernas.jpg"},
    {id: 14, name: 'Licra Corta', plataforma: 'Tela Fria', unidades: 60, genero: 'Ropa Deportiva', price: 150.00, image: "Images/Licra Corta.jpg"},
    {id: 15, name: 'Balón De Voleibol', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 250.00, image: "Images/Balón De Voleibol.jpg"},
    {id: 16, name: 'Balón Fútbol Americano', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 300.00, image: "Images/Balón Fútbol Americano.jpg"},
    {id: 17, name: 'Balón Basketball', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 300.00, image: "Images/Balón Basketball.jpg"},
    {id: 18, name: 'Balón Fut Sala', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 250.00, image: "Images/Balón FutSala.jpg"},
    {id: 19, name: 'Balón Fútbol', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 300.00, image: "Images/Balón Fútbol.jpg"},
    {id: 20, name: 'Pelota Tenis', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 50.00, image: "Images/Pelota Tenis.jpg"},
    {id: 21, name: 'Pelota Badminton', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 100.00, image: "Images/Pelota Badminton.jpg"},
    {id: 22, name: 'Pelota Ping Pong', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 50.00, image: "Images/Pelota Ping Pong.jpg"},
    {id: 23, name: 'Pelota Squash', plataforma: 'Profesional', unidades: 60, genero: 'Balones', price: 50.00, image: "Images/Pelota Squash.jpg"},
    {id: 24, name: 'Raqueta Tenis', plataforma: 'Profesional', unidades: 60, genero: 'Raquetas', price: 300.00, image: "Images/Raqueta Tenis.jpg"},
    {id: 25, name: 'Raqueta Badminton', plataforma: 'Profesional', unidades: 60, genero: 'Raquetas', price: 300.00, image: "Images/Raqueta Badminton.jpg"},
    {id: 26, name: 'Raqueta Ping Pong', plataforma: 'Profesional', unidades: 60, genero: 'Raquetas', price: 300.00, image: "Images/Raqueta Pinp Pong.jpg"},
    {id: 27, name: 'Raqueta Nieve', plataforma: 'Profesional', unidades: 60, genero: 'Raquetas', price: 400.00, image: "Images/Raqueta Nieve.jpg"},
    {id: 28, name: 'Raqueta Squash', plataforma: 'Profesional', unidades: 60, genero: 'Raquetas', price: 300.00, image: "Images/Raqueta Squash.jpg"},
    {id: 29, name: 'Esparadrapo', plataforma: 'Tela', unidades: 60, genero: 'Protección', price: 80.00, image: "Images/Esparadrapo.jpg"},
    {id: 30, name: 'Lilimento', plataforma: 'Spray', unidades: 60, genero: 'Protección', price: 100.00, image: "Images/Lilimento.jpg"},
    {id: 31, name: 'Vendas Elásticas', plataforma: 'Tela Elásticas', unidades: 60, genero: 'Protección', price: 70.00, image: "Images/vendas elasticas.jpg"},
    {id: 32, name: 'Rodilleras', plataforma: 'Profesional', unidades: 60, genero: 'Protección', price: 80.00, image: "Images/Rodilleras.jpg"},
    {id: 33, name: 'Coderas', plataforma: 'Profesional', unidades: 60, genero: 'Protección', price: 50.00, image: "Images/Coderas.jpg"},
    {id: 34, name: 'Muñequeras', plataforma: 'Profesional', unidades: 60, genero: 'Protección', price: 60.00, image: "Images/Muñequeras.jpg"},
    {id: 35, name: 'Casco', plataforma: 'Profesional', unidades: 60, genero: 'Protección', price: 200.00, image: "Images/casco de biclieta.jpg"},
];